name: Build & Deploy Next.js App to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸŒ± Checkout to the branch
        uses: actions/checkout@v4

      - name: ğŸ Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: âš™ï¸ Install dependencies
        run: |
          cd ./src
          npm install

      - name: âš™ï¸ Build Next.js app
        run: |
          cd ./src
          npm run build

      # Ensure the deploy directory exists and copy necessary files for deployment
      - name: ğŸ“‚ Prepare site deployment directory
        run: |
          mkdir -p ./site-deploy/.next
          cp -R ./src/.next/standalone ./site-deploy/.next/
          cp -R ./src/.next/static ./site-deploy/.next/static/
          cp -R ./src/public ./site-deploy/public/
          cp ./src/package.json ./site-deploy/
          cp ./src/next.config.js ./site-deploy/

      - name: ğŸ“¦ Package Next application
        run: |
          cd ./site-deploy
          zip -r Nextjs-site.zip ./*

      - name: ğŸ” Diagnostics
        run: |
          ls ./site-deploy

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: Nextjs-site

      - name: Unzip artifact for deployment
        run: unzip Nextjs-site.zip -d ./deployed-site

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'azchatext-webapp-am3s7wpx6u3ds'
          slot-name: 'Production'
          package: './deployed-site'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_42F294CCE44C492090553227CC006044 }}
